# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'demoReactNative' do

  config = use_native_modules!

  # Pod for epothekeDemo
  pod 'epotheke-sdk','>= 1.1.10'

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )


  target 'demoReactNativeTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Find bitcode_strip
    bitcode_strip_path = `xcrun -sdk iphoneos --find bitcode_strip`.chop!
 
    # Find path to TwilioVideo dependency
    path = Dir.pwd
    framework_path = "#{path}/Pods/epotheke-sdk/epotheke.xcframework/ios-arm64/epotheke.framework/epotheke"
 
    # Strip Bitcode sections from the framework
    strip_command = "#{bitcode_strip_path} #{framework_path} -r -o #{framework_path}"
    puts "About to strip: #{strip_command}"
    system(strip_command)

    framework_path = "#{path}/Pods/open-ecard/OpenEcard.xcframework/armv7_arm64/OpenEcard.framework/OpenEcard"
 
    # Strip Bitcode sections from the framework
    strip_command = "#{bitcode_strip_path} #{framework_path} -r -o #{framework_path}"
    puts "About to strip: #{strip_command}"
    system(strip_command)



  end
end
