workflow:
    rules:
    - if: $CI_MERGE_REQUEST_TITLE =~ /^WIP.*$/
      when: never
    - if: $CI_MERGE_REQUEST_TITLE =~ /^Draft.*$/
      when: never
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_BRANCH == "main"

variables:
    CACHE_KEY: "epotheke-sdk-cache"
    CACHE_TMP_KEY: "epotheke-sdk-cache-$CI_COMMIT_REF_SLUG"
    OEC_OSX_CACHE: "epotheke-osx-cache"

stages:
    - compile
    - test
    - publish

include:
    - project: 'ec/gitlab-ci-templates'
      ref: main
      file: '/templates/.gitlab-ci-build.yml'
    - project: 'ec/gitlab-ci-templates'
      ref: main
      file: '/templates/.gitlab-ci-deployment.yml'
    - '/ci/versioning.yml'
    - '/ci/compile.yml'
    - '/ci/test.yml'
    - '/ci/publish.yml'
