package com.epotheke.erezept.model


enum class GenericErrorResultType(val value: String) {
    INVALID_MESSAGE_DATA("INVALID_MESSAGE_DATA"), 
    TI_UNAVAILABLE("TI_UNAVAILABLE"), 
    TI_SERVICE_ERROR("TI_SERVICE_ERROR"), 
    CARD_EXPIRED("CARD_EXPIRED"), 
    CARD_REVOKED("CARD_REVOKED"), 
    CARD_INVALID("CARD_INVALID"), 
    CARD_ERROR("CARD_ERROR"), 
    UNKNOWN_ERROR("UNKNOWN_ERROR");
}
