# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'EpothekeDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EpothekeDemo
  pod 'open-ecard', '>= 2.3.0-rc.6'
  pod 'epotheke-sdk', :path => '/Users/florianotto/epotheke/epotheke-sdk/sdk/build/cocoapods/publish/debug'


end
