# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'epothekeDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for epothekeDemo
  pod 'epotheke-sdk','>= 1.1.8'


end

