== Error Handling

Except `PrescriptionFetchError` (see below) all possible errors during executions of SDK functionality can be handled by catching exceptions thrown by the functions of `CardLinkProtocols`.
Note that an exception always means that the ongoing call is aborted and can't be recovered.
A new attempt means calling the function again, starting over.

=== establishCardLink()
`establishCardLink` can throw two types of Exceptions:
- `CardLinkClientError` which indicates a problem on client side without server communication
- `CardLinkError` indicating that the epotheke service responded with an error

Both types have subclasses providing more detailed information.

==== CardLinkClientError subclasses

|===
|Classname | Info

|CanStepInterrupted
|The CAN based channel establishment was interrupted

|CardRemoved
|The card was removed or connection was interrupted

|CardInsufficient
|The provided card is not sufficient

|OtherPaceError
|Error during PACE

|OtherNfcError
|Error during NFC communication

|Timeout
|A timeout happened

|OtherClientError
|An error happened on client side
|===

All classes carry a `message` property providing information.
In addition, all may carry a `cause` property carrying the underlying exception.


==== CardLinkError subclasses
If the service answers with an error code, the SDK transfers this code to one of the following exceptions:

|===
|Classname | Info

|NotFound
|Requested Entity Not found

|SicctError
|SICCT service returns an error

|ProcessAlreadyStarted
|Register eGK process is already ongoing

|UnknownWebsocketMessage
|Unknown Web Socket message

|InvalidWebsocketMessage
|Invalid Web Socket message, can occur if required data are missing or message encoding is wrong

|EgkLimitReached
|Limit of 10 eGKs per session reached

|SessionExpired
|session time has exceeded the permissible 15 minutes

|ExpiredCertificate
|Expired eGK certificate

|InvalidCertificate
|Invalid eGK certificate (signature invalid, not a valid eGK certificate, ...)

|CertificateValidityMismatch
|Mismatch between certificate validity periods of X.509 and CVC

|InvalidGdo
|Invalid EF.GDO

|IccsnMismatch
|Mismatch between ICCSN in CV certificate and EF.GDO

|InvalidEfAtr
|Invalid EF.ATR

|UnableToSendSms
|Unable to send SMS for Tan validation

|NotAdmissibleTelPrefix
|Not admissible telephone number prefix, only +49... is allowed

|UnknownError
|Unknown error, probably an internal server error happened or used on an unknown result code

|TanExpired
|Tan has expired

|TanRetryLimitExceeded
|Tan retry limit exceeded

|ServerTimeout
|If the client does not receive an APDU message from the CardLink service

|===

=== fetchPrescriptions
`fetchPrescriptions` can throw `PrescriptionProtocolException` which carries a `genericErrorMessage` property and an optional `cause` property.
`cause` may reference an underlying exception.

`genericErrorMessage` carries a `GenericErrorMessage` object which provides an `errorCode` and an `errorMessage`.

The possible codes are:

- INVALID_MESSAGE_DATA
- TI_UNAVAILABLE
- TI_SERVICE_ERROR
- CARD_EXPIRED
- CARD_REVOKED
- CARD_INVALID
- CARD_ERROR
- UNSUPPORTED_ENVELOPE
- NO_PRESCRIPTIONS_AVAILABLE
- NOT_FOUND
- UNKNOWN_ERROR

==== PrescriptionFetchError
In addition to the `prescriptionBundelList` in `AvailablePrescriptionList` there is an optional property `fetchErrors` which may contain a list of `PrescriptionFetchError`.
These errors indicate errors which did not happen in epotheke service but in third-party services and are associated to specific prescriptions.
A `PrescriptionFetchError` object contains the `prescriptionId` of the associated Prescription, an `errorCode` and an `errorMessage`.
The possible codes are:

- TI_FORBIDDEN
- TI_PRESCRIPTION_NOT_FOUND
- TI_TOO_MANY_REQUESTS_SENT
- TI_INTERNAL_SERVER_ERROR
- TI_UNKNOWN_ERROR
- CONNECT_TIMEOUT_ERROR
- SERIALIZATION_ERROR
- UNKNOWN_ERROR

=== CancellationException
Note that both functions `establishCardLink`  and `fetchPrescriptions` may also throw a CancellationException due to the fact that these methods are implemented as suspendable functions in kotlin coroutines.

=== iOS specific error handling
Exceptions from the epotheke SDK are provided to iOS platforms within `NSError` objects.
Within those `NSError` objects the `domain` property is set to `KotlinException` and the exception itself can be obtained via `userInfo` with the key: "KotlinException".
An example on how to make use of this can be found in the demo code `demo-ios-standalone`.

