== Overview
The epotheke SDK provides an API which can be integrated by using `Epotheke` class.
For exact details please refer to the `android-demo-standalone` or `ios-demo-standalone` example apps.

image::SDK_interfaces.svg[title="epotheke SDK Overview", width=900, align=center]

=== Epotheke
The following has to be provided for creating an instance of `Epotheke`:

- An instance of `TerminalFactory` for NFC functionality which can be obtained by calling `instance()` function of the `AndroidTerminalFactory` class for android and `IosTerminalFactory` for iOS.
- The serviceUrl of the epotheke service
- A tenantToken for accessing the service
- An optional wsSessionId to reconnect to previous session

Once created the protocol implementations `CardlinkAuthenticationProtocol` and `PrescriptionProtocol` can be obtained.

=== Cardlink
The `CardlinkAuthenticationProtocol` allows to call `establishCardlink()` which creates a new cardlink session at the server and registers and associates an eGK card with it by using an SMS/Tan procedure.
A second call with the same session can be used to add another eGK card to the session.
The function returns a `CardlinkAuthResult` which contains information about the session and the registered card.
Since users have to provide data to this process and have to present the eGK card to the device when needed, an implementation of `UserInteraction` has to be provided.
This allows the process to request data and give instructions when needed, but allows the application code to decide how these events are presented or performed exactly.

==== CardLinkAuthResult
The `CardlinkAuthResult` carries the following properties.
|===
|Property | Meaning


|personalData: PersoenlicheVersichertendaten
|The xml data of the insuree as specified by eGK specifications

|insurerData: AllgemeineVersicherungsdaten
|The xml data of the insurance as specified by eGK specifications

|cardSessionId: String,
|A session token

|iccsn: String,
|The iccsn of the used card.

|iccsnReassignmentTimestamp: String,
|If the card was used in the past with a different phone number, this timestamp shows when the new phonenumber was associated with the card.

|wsSessionId: String,
|A session token for the connection. This token can be used to reestablish a past session, if the `Epotheke` instance is newly instantiated.

|===

Note that the reading of `personalData` and `insurerData` is switched off by default and the corresponding properties will be null.
To configure the reading, a reference of  `CardlinkAuthenticationConfig` can be obtained which has the properties: `readPersonalData` and `readInsurerdata`.
Setting those properties to `true` before calling `establishCardLink` will result in reading the values during card communications.


==== User interaction
The `UserInteraction` interface consists of the following functions.

|===
|Function | Meaning | Notes

|onPhoneNumberRequest(): String
|A phone number has to be provided.
|

|onPhoneNumberRetry(resultCode: ResultCode, msg: String?): String
|The provided number was invalid.
|Retrying is possible. The provided `resultCode` and `msg` provide information about what went wrong.

|onTanRequest(): String
|The TAN which was sent to the number via SMS has to be provided.
|

|onTanRetry(resultCode: ResultCode, msg: String?): String
|There was a problem with the provided TAN.
|Retrying is possible. The provided `resultCode` and `msg` provide information about what went wrong.,

|requestCardInsertion()
|The eGK should be presented.
|

|onCardRecognized()
|A connection with the card was established.
|

|onCanRequest(): String
|The CAN for the card is needed.
|

|onCanRetry(resultCode: CardCommunicationResultCode): String
|The CAN was wrong or invalid.
|Retrying is possible. The `resultCode` provides information about what went wrong.

|===

=== Prescriptions
The `PrescriptionProtocol` allows to call `requestPrescriptions()` which will fetch all available prescriptions for all cards added to a session.
The result of `requestPrescriptions()` is an `AvailablePrescriptionLists` object which provides a list of `AvailablePrescriptionList` objects, one for each card which is added to a cardlink session.
The latter contains a list of `PrescriptionBundle` available for the eGK card.
Details of these objects and their attributes can be found in the `PrescriptionModel.kt` file.
