== App Project Setup for using epotheke SDK

=== Android

In addition to the following, please also refer to the demo implementation in `./demo-android-standalone`.

The epotheke SDK for Android is published in a maven repository which can be added to the gradle build as follows:

[source,kotlin]
----
repositories {
    maven {
        url = uri("https://mvn.ecsec.de/repository/openecard-public")
    }
}
----

The dependency must be defined as follows in the gradle file’s dependency section:

[source,kotlin,subs="+attributes"]
----
implementation("com.epotheke:sdk:{release}")
----

Note that
----
implementation("com.epotheke:sdk:{release}"){
    exclude(group = "io.github.oshai", module = "kotlin-logging-android-debug")
}
----
is needed if duplicate class errors appear during build.

Logging is performed with the https://www.slf4j.org/[SLF4J API].
In order to actually emit log messages, an implementation of the API such as https://logback.qos.ch/[Logback] or a wrapper for another logging system can be provided in the application.
Details can be found in the SLF4J or Logback documentation.
SLF4J must be added as a dependency, as it is not packed into the JAR file in order to not raise conflicts in case it is already used in the app.
Logback is optional in case no logging of the Open eCard Framework is needed:

[source,kotlin]
----

implementation("io.github.oshai:kotlin-logging-android:7.0.13")
implementation("com.github.tony19:logback-android:3.0.0")
----

An example of a Logback configuration file (logback.xml) can be found in the assets directory of the demo implementation.

The minimum Android API version to run the epotheke SDK is 21.
It is however possible to build an app with a lower API level.
In that case it must be checked manually, which API level the mobile supports before trying to initialize the epotheke SDK.

The manifest file of the app using the epotheke SDK must contain the following line to enable NFC and internet access of the device:

[source,xml]
----
<uses-permission android:name="android.permission.NFC" />
<uses-permission android:name="android.permission.INTERNET" />
----

==== NFC handling
Due to the way Android implements NFC communications within activities, the method `onNewIntent` must be overridden by the client app to obtain an intent for NFC communication, which cannot be done within the SDK.
To provide this intent to the SDK the `AndroidTerminalFactory` provides a property `tagIntentHandler`, which is a function that has to be called within `onNewIntent`.
All further handling is then done within the SDK.

=== iOS

In addition to the following, please also refer to the demo implementation in `./demo-ios-standalone`.

epotheke SDK is available via https://cocoapods.org/[CocoaPods].
Within the Podfile the following has to be specified:

[source,subs="+attributes"]
----
pod 'epotheke-sdk', '~> {release}'
----

Since the framework uses NFC technology, within "Capabilities and Signing" the "Near field communication" capability has to be activated.

As described in the https://developer.apple.com/documentation/corenfc/nfciso7816tag[Apple Developer documentation], the app must include the following to be able to detect and communicate with ISO7816 tags:

The Near Field Communication Tag Reader Session Formats Entitlement:

[source,xml]
----
<key>com.apple.developer.nfc.readersession.formats</key>
<array>
    <string>TAG</string>
</array>
----

A list of supported application identifiers of ISO7816 tags within the Info.plist file:

[source,xml]
----
<key>com.apple.developer.nfc.readersession.iso7816.select-identifiers</key>
<array>
    <string>D27600000102</string>
    <string>D2760001448000</string>
    <string>D27600014407</string>
    <string>D27600014408</string>
    <string>D2760001440A</string>
    <string>D2760001440B</string>
    <string>D2760001440C</string>
    <string>A000000167455349474E</string>
    <string>D27600006601</string>

</array>
----

The Info.plist must also contain the `<NFCReaderUsageDescription>` key with a value properly explaining the need for the NFC usage.

[source,xml]
----
<key>NFCReaderUsageDescription</key>
<string>Communication with eGK for authentication purposes</string>
----

The corresponding protocol definitions of the API described in this document can be found within the bundle in the "Headers" folder.

==== NFC overlay messages
During NFC communications iOS shows an overlay with an animation, indicating NFC communications.
This overlay allows to set and update messages for the user.
epotheke SDK is updating those messages at specific points during the process.
To adjust the messages a reference to `IosNfcAlertMessages` can be obtained which allows to override its properties which are used as these messages.
The properties are:


|===
|Property | Default | Event

|provideCardMessage
|"Please provide card"
|Card is needed

|cardInsertedMessage
|"Card inserted"
|Card was detected

|cardNotSupported
|"Card not supported"
|Card is not supported

|cardConnectedMessage
|"Card connected"
|Card connected successfully

|nfcErrorMessage
|"NFC error"
|An error happened

|nfcCompletionMessage
|"Communication completed"
|Process is ready

|===
