== App Project Setup for using epotheke SDK

=== Android

In addition to the following, please also refer to the demo implementation in `./demo-android-standalone`.

The epotheke SDK for Android is published in a maven repository which can be added to the gradle build as follows:

[source,kotlin]
----
repositories {
    maven {
        url = uri("https://mvn.ecsec.de/repository/openecard-public")
    }
}
----

The dependency must be defined as follows in the gradle file’s dependency section:

[source,kotlin,subs="+attributes"]
----
implementation("com.epotheke:sdk:{release}")
----

Logging is performed with the https://www.slf4j.org/[SLF4J API].
In order to actually emit log messages, an implementation of the API such as https://logback.qos.ch/[Logback] or a wrapper for another logging system can be provided in the application.
Details can be found in the SLF4J or Logback documentation.
SLF4J must be added as a dependency, as it is not packed into the JAR file in order to not raise conflicts in case it is already used in the app.
Logback is optional in case no logging of the Open eCard Framework is needed:

[source,kotlin]
----
implementation("org.slf4j:slf4j-api:1.7.26")
implementation("com.github.tony19:logback-android:1.3.0-2")
----

An example of a Logback configuration file (logback.xml) can be found in the assets directory of the demo implementation.

Due to the number of methods in the referenced libraries being greater than 65.536, MultiDex support must be enabled for Android apps which support an API level below 21.
The following statement has to be added to the gradle file:

[source,kotlin]
----
android {
    defaultConfig {
        multiDexEnabled = true
    }
}
----

Since the epotheke SDK has been compiled for Java 8, the following entry is needed:

[source,kotlin]
----
compileOptions {
    sourceCompatibility = "1.8"
    targetCompatibility = "1.8"
}
----

The minimum Android API version to run the epotheke SDK is 21.
It is however possible to build an app with a lower API level.
In that case it must be checked manually, which API level the mobile supports before trying to initialize the epotheke SDK.

The manifest file of the app using the epotheke SDK must contain the following line to enable NFC and internet access of the device:

[source,xml]
----
<uses-permission android:name="android.permission.NFC" />
<uses-permission android:name="android.permission.INTERNET" />
----



=== iOS

In addition to the following, please also refer to the demo implementation in `./demo-ios-standalone`.

The epotheke SDK for iOS is delivered as a Swift and ObjC compatible framework which can be added to a project in XCode.
The framework must then be "embedded and signed" during the build phase of XCode.

As an alternative the framework is also available via https://cocoapods.org/[CocoaPods].
Within the Podfile the following has to be specified:

[source,subs="+attributes"]
----
pod 'epotheke-sdk', '~> {releaseMinor}'
----

Since the framework uses NFC technology, within "Capabilities and Signing" the "Near field communication" capability has to be activated.

As described in the https://developer.apple.com/documentation/corenfc/nfciso7816tag[Apple Developer documentation], the app must include the following to be able to detect and communicate with ISO7816 tags:

The Near Field Communication Tag Reader Session Formats Entitlement:

[source,xml]
----
<key>com.apple.developer.nfc.readersession.formats</key>
<array>
    <string>TAG</string>
</array>
----

A list of supported application identifiers of ISO7816 tags within the Info.plist file:

[source,xml]
----
<key>com.apple.developer.nfc.readersession.iso7816.select-identifiers</key>
<array>
    <string>D27600000102</string>
    <string>D2760001448000</string>
    <string>D27600014407</string>
    <string>D27600014408</string>
    <string>D2760001440A</string>
    <string>D2760001440B</string>
    <string>D2760001440C</string>
    <string>A000000167455349474E</string>
    <string>D27600006601</string>

</array>
----

The Info.plist must also contain the `<NFCReaderUsageDescription>` key with a value properly explaining the need for the NFC usage.

[source,xml]
----
<key>NFCReaderUsageDescription</key>
<string>Communication with eGK for authentication purposes</string>
----

The corresponding protocol definitions of the API described in this document can be found within the bundle in the "Headers" folder.

