# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS_OeC_testApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS_OeC_testApp
  pod 'open-ecard', '>= 2.3.0-rc.6'
  pod 'epotheke-sdk', '>= 1.1.3'

end
